### ISSUE TITLE
FEATURE: Get HMD, HFD, HFC data programmatically 

### ISSUE THREAD

**Issue by chacalle** [ihmeuw-demographics/demUtils#36]
**Is your feature request related to a problem? Please describe.**
We want to be able to download HMD, HFD, HFC data programmatically from R.

**Describe the solution you'd like**
See if [`HMDHFDplus`](https://cran.r-project.org/web/packages/HMDHFDplus/HMDHFDplus.pdf) provides the functionality we want. If not create our own scraping functions. 

Also create scraping functions to help identify when and where there are updates to download.

**Additional context**
See @hcomfo95's comments about how HFD, HFC data are currently downloaded. https://github.com/ihmeuw-demographics/demUtils/pull/34

**Comment by krpaulson** [comment]
I've done this before:
```
# set HMD username and password
myusername <- "yourusername"
mypassword <- "yourpassword"

# load data from web
country_codes <- HMDHFDplus::getHMDcountries()
dt <- data.table()
for(cc in country_codes) {
  for(ss in c("m", "f")) {
    temp <- HMDHFDplus::readHMDweb(
      CNTRY = cc,
      item = paste0(ss, "ltper_1x1"),
      username = myusername,
      password = mypassword
    )
    temp <- as.data.table(temp)
    temp[, iso3 := cc]
    temp[, sex := ifelse(ss == "m", "male", "female")]
    dt <- rbind(dt, temp, fill = T)
  }
}
dt <- dt[, list(iso3, year_start = Year, sex, age_start = Age, qx)]
```

Do you think it's work writing a wrapper function to do this?

**Comment by chacalle** [comment]
This worked great, so used `HMDHFDplus` directly
